export const ReportConstants = {
  GET_REPORT_REQUEST: 'GET_REPORT_API_REQUEST',
  GET_REPORT_SUCCESS: 'GET_REPORT_API__SUCCESS',
  GET_REPORT_FAILURE: 'GET_REPORT_API__FAILURE',
  CLEAR_REPORT_RESPONSE: 'CLEAR_REPORT_RESPONSE',
  SET_SELECTED_ASSET_ID: 'SELECTED_ASSET_ID',
  SET_ACTIVE_REPORT: 'SET_ACTIVE_REPORT',
  GET_ENGINE_CONDITION_REPORT_SUCCESS:
    'GET_ENGINE_CONDITION_REPORT_API__SUCCESS',
  GET_ENGINE_MAINTAINANCE_REPORT_SUCCESS:
    'GET_ENGINE_MAINTAINANCE_REPORT_API__SUCCESS',
  GET_FINANCE_ADMIN_REPORT_SUCCESS: 'GET_FINANCE_ADMIN_REPORT_API__SUCCESS',
  GET_FLIGHT_OPERATION_REPORT_SUCCESS:
    'GET_FLIGHT_OPERATION_REPORT_API__SUCCESS',
  GET_FLIGHT_SAFETY_REPORT_SUCCESS: 'GET_FLIGHT_SAFETY_REPORT_API__SUCCESS',
  GET_FLIGHT_MOQA_REPORT_SUCCESS: 'GET_FLIGHT_MOQA_REPORT_API__SUCCESS',
  GET_FLIGHT_FOQA_REPORT_SUCCESS: 'GET_FLIGHT_FOQA_REPORT_API__SUCCESS',
};

export const PlanConstants = {
  POST_CREATE_LAYER_REQUEST: 'POST_CREATE_LAYER_REQUEST',
  GET_CREATE_LAYER_SUCCESS: 'GET_CREATE_LAYER_API__SUCCESS',
  GET_CREATE_LAYER_FAILURE: 'GET_CREATE_LAYER_API__FAILURE',
};
export const ViewsConstants = {
FLIGHT_LIST_DATA:'VIEW_FLIGHT_LIST_DATA',
VIEW_CLEAR_DATA:'VIEW_CLEAR_DATA',
BARON_WEATHER_DATA:'BARON_WEATHER_DATA',
VIEW_FLIGHT_SPEED_DETAILS : 'VIEW_FLIGHT_SPEED_DETAILS'
}

export const EDIT_VIEW_LANDMARK_DATA = 'EditViewLandmarkData';
