export const ReportConstants = {
  GET_REPORT_REQUEST: "GET_REPORT_API_REQUEST",
  GET_REPORT_SUCCESS: "GET_REPORT_API__SUCCESS",
  GET_REPORT_FAILURE: "GET_REPORT_API__FAILURE",
  CLEAR_REPORT_RESPONSE: "CLEAR_REPORT_RESPONSE",
  SET_SELECTED_ASSET_ID: "SELECTED_ASSET_ID",
  SET_ACTIVE_REPORT: "SET_ACTIVE_REPORT",
  GET_ENGINE_CONDITION_REPORT_SUCCESS:
    "GET_ENGINE_CONDITION_REPORT_API__SUCCESS",
  GET_ENGINE_MAINTAINANCE_REPORT_SUCCESS:
    "GET_ENGINE_MAINTAINANCE_REPORT_API__SUCCESS",
  GET_FINANCE_ADMIN_REPORT_SUCCESS: "GET_FINANCE_ADMIN_REPORT_API__SUCCESS",
  GET_FLIGHT_OPERATION_REPORT_SUCCESS:
    "GET_FLIGHT_OPERATION_REPORT_API__SUCCESS",
  GET_FLIGHT_SAFETY_REPORT_SUCCESS: "GET_FLIGHT_SAFETY_REPORT_API__SUCCESS",
  GET_FLIGHT_MOQA_REPORT_SUCCESS: "GET_FLIGHT_MOQA_REPORT_API__SUCCESS",
  GET_FLIGHT_FOQA_REPORT_SUCCESS: "GET_FLIGHT_FOQA_REPORT_API__SUCCESS",
  REPORT_SELECTED_FLIGHT: "REPORT_SELECTED_FLIGHT",
};

export const PlanConstants = {
  POST_CREATE_LAYER_REQUEST: "POST_CREATE_LAYER_REQUEST",
  GET_CREATE_LAYER_SUCCESS: "GET_CREATE_LAYER_API__SUCCESS",
  GET_CREATE_LAYER_FAILURE: "GET_CREATE_LAYER_API__FAILURE",
};
export const ViewsConstants = {
  FLIGHT_LIST_DATA: "VIEW_FLIGHT_LIST_DATA",
  VIEW_ASSET_LIST: "VIEW_ASSET_LIST",
  VIEW_SELECTED_ASSET: "VIEW_SELECTED_ASSET",
  VIEW_CLEAR_DATA: "VIEW_CLEAR_DATA",
  BARON_WEATHER_DATA: "BARON_WEATHER_DATA",
  VIEW_FLIGHT_SPEED_DETAILS: "VIEW_FLIGHT_SPEED_DETAILS",
  START_TIMER: "START_TIMER",
  VIEW_SELECTED_EVENT: "VIEW_SELECTED_EVENT",
  UPDATE_MAP_TYPE_ID: "UPDATE_MAP_TYPE_ID",
  VIEW_MOVE_TO_ASSET: "VIEW_MOVE_TO_ASSET",
  VIEW_ZOOM_TO_ASSET: "VIEW_ZOOM_TO_ASSET",
  VIEW_LAST_REFRESHED_TIME: "VIEW_LAST_REFRESHED_TIME",
  VIEW_ZOOM_IN_TRIGGER: "VIEW_ZOOM_IN_TRIGGER",
  VIEW_ZOOM_OUT_TRIGGER: "VIEW_ZOOM_OUT_TRIGGER",
};

export const EDIT_VIEW_LANDMARK_DATA = "EditViewLandmarkData";

export const DefaultMapID = "hybrid";
export const MAP_ID_OPTIONS = [
  { id: "roadmap", label: "Map Roadmap" },
  { id: "satellite", label: "Map Satellite" },
  { id: "hybrid", label: "Map Hybrid" },
  { id: "terrain", label: "Map Terrain" },
  { id: "styled_map", label: "Map Styled_map" },
];
