export const ReportConstants = {
  GET_REPORT_REQUEST: 'GET_REPORT_API_REQUEST',
  GET_REPORT_SUCCESS: 'GET_REPORT_API__SUCCESS',
  GET_REPORT_FAILURE: 'GET_REPORT_API__FAILURE',
  CLEAR_REPORT_RESPONSE: 'CLEAR_REPORT_RESPONSE',
};
